version: "3.3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chnage_it
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: chnage_it
    networks:
      - wpsite  
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 10s
      retries: 3

  wordpress:
    depends_on:  
      - db
    build: .    
    volumes:
      - wp-content:/var/www/html/wp-content
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: change_it
      WORDPRESS_DB_NAME: wordpress
    healthcheck:
      test: "wget -O /dev/null http://localhost || exit 1"
      interval: 10s
      retries: 3  
    networks:
      - wpsite

volumes:
  db_data: {}
  wp-content: {}

networks:
  wpsite: 
